ENVIRONMENT: local
LOG_LEVEL: info
PORT: 3050
GRPC_PORT: 9091
SERVICE_NAME: valuations-api
SERVICE_VERSION: "1.0.0"
DB:
  USER: dimo
  PASSWORD: dimo
  PORT: 5432
  HOST: localhost
  NAME: valuations_api
  MAX_OPEN_CONNECTIONS: 5
  MAX_IDLE_CONNECTIONS: 5
TRACE_MONITOR_VIEW: http://localhost:14268/api/traces
MONITORING_PORT: 8866
KAFKA_BROKERS: 127.0.0.1:9092
DBC_DECODING_TOPIC: topic.dbc.decoding

NATS_URL: http://localhost:4222
NATS_STREAM_NAME: DATA-DOWNLOAD
NATS_DATA_DOWNLOAD_SUBJECT: data-download
NATS_DURABLE_CONSUMER: data-download-durable
NATS_ACK_TIMEOUT: 2m

VINCARIO_API_URL: https://api.vindecoder.eu/3.2
VINCARIO_API_KEY:
VINCARIO_API_SECRET: X

DRIVLY_VIN_API_URL: https://vin.dev.driv.ly
DRIVLY_OFFER_API_URL: https://offers.dev.driv.ly
DRIVLY_API_KEY: xxx

DEVICE_DEFINITIONS_GRPC_ADDR: localhost:8086
