ENVIRONMENT: local
LOG_LEVEL: info
PORT: 3050
GRPC_PORT: 9091
MONITORING_PORT: 8866
SERVICE_NAME: valuations-api
SERVICE_VERSION: "1.0.0"
DB:
  USER: dimo
  PASSWORD: dimo
  PORT: 5432
  HOST: localhost
  NAME: valuations_api
  MAX_OPEN_CONNECTIONS: 5
  MAX_IDLE_CONNECTIONS: 5

JWT_KEY_SET_URL: https://auth.dev.dimo.zone/keys # dev
#JWT_KEY_SET_URL: http://127.0.0.1:5556/keys

VINCARIO_API_URL: https://api.vindecoder.eu/3.2
VINCARIO_API_KEY:
VINCARIO_API_SECRET: X

DRIVLY_VIN_API_URL: https://vin.dev.driv.ly
DRIVLY_OFFER_API_URL: https://offers.dev.driv.ly
DRIVLY_API_KEY: xxx

DEVICE_DEFINITIONS_GRPC_ADDR: localhost:8086
DEVICES_GRPC_ADDR: localhost:8087
DEVICE_DATA_GRPC_ADDR: localhost:8088
GOOGLE_MAPS_API_KEY: X

NATS_URL: http://localhost:4222
NATS_STREAM_NAME: VALUATIONS-REQUEST
NATS_VALUATION_SUBJECT: valuations-request
NATS_ACK_TIMEOUT: 2m
NATS_DURABLE_CONSUMER: valuations-request-durable

IDENTITY_API_URL: https://identity-api.dev.dimo.zone/query
TELEMETRY_API_URL: https://telemetry-api.dev.dimo.zone/query