ENVIRONMENT: local
LOG_LEVEL: info
PORT: 3050
GRPC_PORT: 9091
MONITORING_PORT: 8866
SERVICE_NAME: valuations-api
SERVICE_VERSION: "1.0.0"
DB:
  USER: dimo
  PASSWORD: dimo
  PORT: 5432
  HOST: localhost
  NAME: valuations_api
  MAX_OPEN_CONNECTIONS: 5
  MAX_IDLE_CONNECTIONS: 5
KAFKA_BROKERS: 127.0.0.1:9092
VALUATION_REQUEST_TOPIC: topic.vehicle.valuation.request

VINCARIO_API_URL: https://api.vindecoder.eu/3.2
VINCARIO_API_KEY:
VINCARIO_API_SECRET: X

DRIVLY_VIN_API_URL: https://vin.dev.driv.ly
DRIVLY_OFFER_API_URL: https://offers.dev.driv.ly
DRIVLY_API_KEY: xxx

DEVICE_DEFINITIONS_GRPC_ADDR: localhost:8086
DEVICES_GRPC_ADDR: localhost:8087
DEVICE_DATA_GRPC_ADDR: localhost:8088
GOOGLE_MAPS_API_KEY: X
