apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "valuations-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
    - remoteRef:
        key: {{ .Release.Namespace }}/valuations/db/host
      secretKey: DB_HOST
    - remoteRef:
        key: {{ .Release.Namespace }}/valuations/db/user
      secretKey: DB_USER
    - remoteRef:
        key: {{ .Release.Namespace }}/valuations/db/pass
      secretKey: DB_PASSWORD
    - remoteRef:
        key: {{ .Release.Namespace }}/valuations/vincario/apikey
      secretKey: VINCARIO_API_KEY
    - remoteRef:
        key: {{ .Release.Namespace }}/valuations/vincario/apisecret
      secretKey: VINCARIO_API_SECRET
    - remoteRef:
        key: {{ .Release.Namespace }}/valuations/drivly/apikey
      secretKey: DRIVLY_API_KEY
    - remoteRef:
        key: {{ .Release.Namespace }}/valuations/google/maps-api-key
      secretKey: GOOGLE_MAPS_API_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "valuations-api.fullname" . }}-secret
    template:
      metadata: { }