replicaCount: 2
image:
  repository: dimozone/valuations-api
  pullPolicy: IfNotPresent
  tag: fd0c14b
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all
env:
  ENVIRONMENT: dev
  PORT: '8080'
  GRPC_PORT: '8086'
  LOG_LEVEL: info
  DB_PORT: '5432'
  DB_NAME: valuations_api
  DB_MAX_OPEN_CONNECTIONS: '10'
  DB_MAX_IDLE_CONNECTIONS: '3'
  SERVICE_NAME: valuations-api
  JWT_KEY_SET_URL: https://auth.dev.dimo.zone/keys
  DEPLOYMENT_BASE_URL: https://valuations-api.dev.dimo.zone
  AWS_REGION: us-east-2
  MONITORING_PORT: 8888
  DEVICES_GRPC_ADDR: devices-api-dev:8086
  DEVICE_DEFINITIONS_GRPC_ADDR: device-definitions-api-dev:8086
  DEVICE_DATA_GRPC_ADDR: device-data-api-dev:8086
  NATS_URL: nats-dev:4222
  NATS_STREAM_NAME: DD_VALUATION_TASKS
  NATS_VALUATION_SUBJECT: dd_valuation_tasks
  NATS_VALUATION_DURABLE_CONSUMER: dd-valuation-task-consumer
  NATS_OFFER_SUBJECT: dd_offer_tasks
  NATS_OFFER_DURABLE_CONSUMER: dd-offer-task-consumer
  NATS_ACK_TIMEOUT: 2m
  VINCARIO_API_URL: https://api.vindecoder.eu/3.2
  DRIVLY_VIN_API_URL: https://vin.dev.driv.ly
  DRIVLY_OFFER_API_URL: https://offers.dev.driv.ly
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8888
      targetPort: mon-http
      protocol: TCP
    http:
      port: 8080
      targetPort: http
      protocol: TCP
    grpc:
      port: 8086
      targetPort: grpc
      protocol: TCP
ports:
  - name: mon-http
    containerPort: 8888
    protocol: TCP
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: grpc
    containerPort: 8086
    protocol: TCP
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://app.dev.dimo.zone
    nginx.ingress.kubernetes.io/limit-rps: '5'
    external-dns.alpha.kubernetes.io/hostname: valuations-api.dev.dimo.zone
  hosts:
    - host: valuations-api.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 250m
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
serviceMonitor:
  enabled: true
  path: /metrics
  port: mon-http
  interval: 30s
jobs:
  - name: batch-valuations
    enabled: false
    schedule: 0 0 * * 0
    args:
      - '-c'
      - /valuations-api valuations-pull; CODE=$?; echo "valuations-pull completed"; wget -q --post-data "hello=shutdown" http://localhost:4191/shutdown &> /dev/null; exit $CODE;
