replicaCount: 2
image:
  repository: dimozone/valuations-api
  pullPolicy: IfNotPresent
  tag: 285f871
env:
  ENVIRONMENT: prod
  PORT: '8080'
  LOG_LEVEL: info
  DB_PORT: '5432'
  DB_NAME: valuations_api
  DB_MAX_OPEN_CONNECTIONS: '50'
  DB_MAX_IDLE_CONNECTIONS: '15'
  SERVICE_NAME: valuations-api
  JWT_KEY_SET_URL: https://auth.dimo.zone/keys
  DEPLOYMENT_BASE_URL: https://valuations-api.dimo.zone
  DEVICES_GRPC_ADDR: devices-api-prod:8086
  DEVICE_DEFINITIONS_GRPC_ADDR: device-definitions-api-prod:8086
  DEVICE_DATA_GRPC_ADDR: device-data-api-prod:8086
  USERS_GRPC_ADDR: users-api-prod:8086
  NATS_URL: nats-prod:4222
  NATS_STREAM_NAME: DD_VALUATION_TASKS
  NATS_VALUATION_SUBJECT: dd_valuation_tasks
  NATS_VALUATION_DURABLE_CONSUMER: dd-valuation-task-consumer
  NATS_OFFER_SUBJECT: dd_offer_tasks
  NATS_OFFER_DURABLE_CONSUMER: dd-offer-task-consumer
  NATS_ACK_TIMEOUT: 2m
  VINCARIO_API_URL: https://api.vindecoder.eu/3.2
  DRIVLY_VIN_API_URL: https://vin.dev.driv.ly
  DRIVLY_OFFER_API_URL: https://offers.dev.driv.ly
  TOKEN_EXCHANGE_JWT_KEY_SET_URL: http://dex-roles-rights-prod.prod.svc.cluster.local:5556/keys
  VEHICLE_NFT_ADDRESS: '0xba5738a18d83d41847dffbdc6101d37c69c9b0cf'
  KAFKA_BROKERS: kafka-prod-dimo-kafka-kafka-brokers:9092
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://app.dimo.zone
    nginx.ingress.kubernetes.io/limit-rps: '9'
    external-dns.alpha.kubernetes.io/hostname: valuations-api.dimo.zone
  hosts:
    - host: valuations-api.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
jobs:
  - name: batch-valuations
    enabled: true
    schedule: 0 0 * * 0
    args:
      - '-c'
      - /valuations-api pull-valuations; CODE=$?; echo "pull-valuations completed"; wget -q --post-data "hello=shutdown" http://localhost:4191/shutdown &> /dev/null; exit $CODE;
