// Code generated by MockGen. DO NOT EDIT.
// Source: telemetry_api.go
//
// Generated by this command:
//
//	mockgen -source telemetry_api.go -destination mocks/telemetry_api_mock.go -package mock_gateways
//

// Package mock_gateways is a generated GoMock package.
package mock_gateways

import (
	context "context"
	reflect "reflect"

	gateways "github.com/DIMO-Network/valuations-api/internal/core/gateways"
	gomock "go.uber.org/mock/gomock"
)

// MockTelemetryAPI is a mock of TelemetryAPI interface.
type MockTelemetryAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTelemetryAPIMockRecorder
}

// MockTelemetryAPIMockRecorder is the mock recorder for MockTelemetryAPI.
type MockTelemetryAPIMockRecorder struct {
	mock *MockTelemetryAPI
}

// NewMockTelemetryAPI creates a new mock instance.
func NewMockTelemetryAPI(ctrl *gomock.Controller) *MockTelemetryAPI {
	mock := &MockTelemetryAPI{ctrl: ctrl}
	mock.recorder = &MockTelemetryAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelemetryAPI) EXPECT() *MockTelemetryAPIMockRecorder {
	return m.recorder
}

// GetLatestSignals mocks base method.
func (m *MockTelemetryAPI) GetLatestSignals(ctx context.Context, tokenID uint64, authHeader string) (*gateways.SignalsLatest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestSignals", ctx, tokenID, authHeader)
	ret0, _ := ret[0].(*gateways.SignalsLatest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestSignals indicates an expected call of GetLatestSignals.
func (mr *MockTelemetryAPIMockRecorder) GetLatestSignals(ctx, tokenID, authHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestSignals", reflect.TypeOf((*MockTelemetryAPI)(nil).GetLatestSignals), ctx, tokenID, authHeader)
}

// GetVinVC mocks base method.
func (m *MockTelemetryAPI) GetVinVC(ctx context.Context, tokenID uint64, authHeader string) (*gateways.VinVCLatest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVinVC", ctx, tokenID, authHeader)
	ret0, _ := ret[0].(*gateways.VinVCLatest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVinVC indicates an expected call of GetVinVC.
func (mr *MockTelemetryAPIMockRecorder) GetVinVC(ctx, tokenID, authHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVinVC", reflect.TypeOf((*MockTelemetryAPI)(nil).GetVinVC), ctx, tokenID, authHeader)
}
