apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "valuations-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
    - remoteRef:
        key: {{ .Release.Namespace }}/decoding/db/host
      secretKey: DB_HOST
    - remoteRef:
        key: {{ .Release.Namespace }}/decoding/db/user
      secretKey: DB_USER
    - remoteRef:
        key: {{ .Release.Namespace }}/decoding/db/pass
      secretKey: DB_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "valuations-api.fullname" . }}-secret
    template:
      metadata: { }