// Code generated by MockGen. DO NOT EDIT.
// Source: drivly_valuation_service.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	models "github.com/DIMO-Network/valuations-api/internal/core/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDrivlyValuationService is a mock of DrivlyValuationService interface.
type MockDrivlyValuationService struct {
	ctrl     *gomock.Controller
	recorder *MockDrivlyValuationServiceMockRecorder
}

// MockDrivlyValuationServiceMockRecorder is the mock recorder for MockDrivlyValuationService.
type MockDrivlyValuationServiceMockRecorder struct {
	mock *MockDrivlyValuationService
}

// NewMockDrivlyValuationService creates a new mock instance.
func NewMockDrivlyValuationService(ctrl *gomock.Controller) *MockDrivlyValuationService {
	mock := &MockDrivlyValuationService{ctrl: ctrl}
	mock.recorder = &MockDrivlyValuationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDrivlyValuationService) EXPECT() *MockDrivlyValuationServiceMockRecorder {
	return m.recorder
}

// PullOffer mocks base method.
func (m *MockDrivlyValuationService) PullOffer(ctx context.Context, userDeviceID string) (models.DataPullStatusEnum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullOffer", ctx, userDeviceID)
	ret0, _ := ret[0].(models.DataPullStatusEnum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullOffer indicates an expected call of PullOffer.
func (mr *MockDrivlyValuationServiceMockRecorder) PullOffer(ctx, userDeviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullOffer", reflect.TypeOf((*MockDrivlyValuationService)(nil).PullOffer), ctx, userDeviceID)
}

// PullValuation mocks base method.
func (m *MockDrivlyValuationService) PullValuation(ctx context.Context, userDeiceID, deviceDefinitionID, vin string) (models.DataPullStatusEnum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullValuation", ctx, userDeiceID, deviceDefinitionID, vin)
	ret0, _ := ret[0].(models.DataPullStatusEnum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullValuation indicates an expected call of PullValuation.
func (mr *MockDrivlyValuationServiceMockRecorder) PullValuation(ctx, userDeiceID, deviceDefinitionID, vin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullValuation", reflect.TypeOf((*MockDrivlyValuationService)(nil).PullValuation), ctx, userDeiceID, deviceDefinitionID, vin)
}
