// Code generated by MockGen. DO NOT EDIT.
// Source: location_service.go
//
// Generated by this command:
//
//	mockgen -source location_service.go -destination mocks/location_service_mock.go
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	gateways "github.com/DIMO-Network/valuations-api/internal/core/gateways"
	services "github.com/DIMO-Network/valuations-api/internal/core/services"
	gomock "go.uber.org/mock/gomock"
)

// MockLocationService is a mock of LocationService interface.
type MockLocationService struct {
	ctrl     *gomock.Controller
	recorder *MockLocationServiceMockRecorder
}

// MockLocationServiceMockRecorder is the mock recorder for MockLocationService.
type MockLocationServiceMockRecorder struct {
	mock *MockLocationService
}

// NewMockLocationService creates a new mock instance.
func NewMockLocationService(ctrl *gomock.Controller) *MockLocationService {
	mock := &MockLocationService{ctrl: ctrl}
	mock.recorder = &MockLocationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationService) EXPECT() *MockLocationServiceMockRecorder {
	return m.recorder
}

// GetGeoDecodedLocation mocks base method.
func (m *MockLocationService) GetGeoDecodedLocation(ctx context.Context, signals *gateways.SignalsLatest, tokenID uint64) (*services.LocationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeoDecodedLocation", ctx, signals, tokenID)
	ret0, _ := ret[0].(*services.LocationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeoDecodedLocation indicates an expected call of GetGeoDecodedLocation.
func (mr *MockLocationServiceMockRecorder) GetGeoDecodedLocation(ctx, signals, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeoDecodedLocation", reflect.TypeOf((*MockLocationService)(nil).GetGeoDecodedLocation), ctx, signals, tokenID)
}
