name: Helm Lint and Test Charts

on: pull_request

jobs:
  helm-lint-test:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v5

      - name: helm-check
        uses: igabaydulin/helm-check-action@0.2.0
        env:
          CHART_LOCATION: ./charts/valuations-api
          CHART_VALUES: ./charts/valuations-api/values-prod.yaml